CREATE TABLE IF NOT EXISTS game_funstep(
  `playerId` VARCHAR(36) NOT NULL COMMENT '玩家Id',
  `funstep` MEDIUMBLOB COMMENT '玩家新手记录',
  PRIMARY KEY (`playerId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=16;